[
    '00',  # 00 = '00'
    'Fight\rItem\rSpell\rRun',  # 01 = '戦う\r所持品使用\r呪文\r逃げる'
    'Yes\rNo',  # 02 = 'YES\rNO'
    'Use\rMove\rDiscard',  # 03 = '使う\r移動\r捨てる'
    'Back\rRestart\rSFX',  # 04 = '中止\rリスタート\rＮＯＴＥ'
    'Back\rRestart\rSFX\rMusic',  # 05 = '中止\rリスタート\rＮＯＴＥ\rＢＧＭ'
    'Music ON\rMusic OFF',  # 06 = 'BGM ON\rBGM OFF'
    'SFX ON\rSFX OFF',  # 07 = 'NOTE ON\rNOTE OFF'
    '',  # 08 = '08'
    '',  # 09 = '09'
    '',  # 0a = '0A'
    '',  # 0b = '0B'
    'Save the completion of the game? (Y/N)',  # 0c = 'ゲームの終了をセーブしますか? (Y/N)'
    '        Press Enter to start.',  # 0d = 'リターンキーを押してください。'
    'Game saved.',  # 0e = 'セーブ完了。'
    'Remove the disk and turn off or reboot the device.',  # 0f = 'ディスクを抜き、電源を切ってください。\x15（またはリセットスイッチを押してください。）'
    '10',  # 10 = '10'
    'Average: ',  # 11 = 'AVERAGE: '
    'words/m',  # 12 = 'words/m'
    'Speed(wpm)',  # 13 = 'SPEED(w/m)'
    'Typos(%)',  # 14 = 'MISS(%)'
    'Step',  # 15 = 'STEP'
    'NO DATA',  # 16 = 'NO DATA'
    '',  # 17 = '17'
    'You don\'t have enough spice.',  # 18 = 'スパイスが足りないようですね。'
    '\x18You can\'t carry that.',  # 19 = '\x18持ちきれない。'
    '...???',  # 1a = '………???'
    ' was obtained.\x18',  # 1b = 'を拾った。\x18'
    '1C',  # 1c = '1C'
    'SCORE',  # 1d = 'SCORE'
    '(f=quit)',  # 1e = '(f=中止)'
    '(ff=quit)',  # 1f = '(ff=中止)'
    '20',  # 20 = '20'
    '\x18Insert the disk correctly and press \x15\x16.',  # 21 = '\x18ディスクを正しくセットして、\x15\x16を押して下さい。'
    '\x18No problem here.',  # 22 = '\x18特別な物は何も無い。'
    'Done\r',  # 23 = '終了\r'
    ' key ',  # 24 = 'キー '
    'sp\r',  # 25 = 'sp\r'
    ' key... Oh, you already have one.',  # 26 = 'キーは、もうお持ちになってますよ。'
    'Anything else?',  # 27 = '他にご入り用は?'
    'Thank you.\x15Let\'s equip your ',  # 28 = 'ありがとうございます。\x15では、この'
    ' key, shall we?',  # 29 = 'キーを\x15お取り付けいたしましょう。'
    'Item',  # 2a = '陳列'
    'Held',  # 2b = 'カゴ'
    'Tot.',  # 2c = '合計'
    'Take one\r',  # 2d = '商品を取る\r'
    ' (',  # 2e = '(一個 '
    'spc each)\x18',  # 2f = 'sp)がある。\x18'
    'Got a basket.\x18',  # 30 = 'カゴを取った。\x18'
    'Put back the basket.\x18',  # 31 = 'カゴを置いた。\x18'
    '\x18Your basket is full.',  # 32 = '\x18カゴに入りきらない。'
    '\x18Not carrying anything.',  # 33 = '\x18何も持っていない。'
    '\x18Speed: ',  # 34 = '\x18スピード:   '
    ' wpm\x15',  # 35 = 'ワード/m\x15'
    '\x18(Too many typos.)\x15',  # 36 = '\x18(ミスタイプが多過ぎる。)\x15'
    'Typos: ',  # 37 = 'ミスタイプ: '
    '(',  # 38 = '字('
    '\x18Max EXP went up by ',  # 39 = '\x18経験許容度が '
    ' points.',  # 3a = 'pt.増えた。'
    ' was discarded.\x18',  # 3b = 'を捨てた。\x18'
    '\x18Nothing happens.',  # 3c = '\x18何も起こらない。'
    '\x18You aren\'t hungry.',  # 3d = '\x18お腹が空いていない。'
    'Recovered ',  # 3e = 'LIFE '
    ' hit points.',  # 3f = 'pt.回復。'
    '40',  # 40 = '40'
    '\x18[SAVE POINT]: Save your game?',  # 41 = '\x18[SAVE ZONE]: セーブしますか?'
    '\x18Game saved.',  # 42 = '\x18セーブ完了。'
    '\x18You haven\'t saved your game.\x15Start over from the beginning?',  # 43 = '\x18一度もセーブされていません。\x15最初からやり直しますか?'
    '\x18Start over from your last save point?',  # 44 = '\x18最後にセーブした所からやり直しますか?'
    '\x18Restart',  # 45 = '\x18リスタート'
    'I\'ll buy any items you don\'t want anymore.',  # 46 = '不用になった品物がございましたら\x15買い取りますが…。'
    'Which one?',  # 47 = 'どの品を?'
    ' spice, final offer.',  # 48 = 'スパイスで、いかがでしょう。'
    'Thank you very much.',  # 49 = 'ありがとうございます。'
    'What else?',  # 4a = '…他には?'
    ' was sold.\x18',  # 4b = 'を売った。\x18'
    'You got in bed.\x18',  # 4c = 'ベッドに入った。\x18'
    'You\'re not tired.\x18',  # 4d = '全然眠くない。\x18'
    'Health restored.\x18',  # 4e = '体力回復。\x18'
    'Use:',  # 4f = '使用:'
    '50',  # 50 = '50'
    'Name:',  # 51 = 'NAME:'
    '\x18There\'s an HP box here. Take it?',  # 52 = '\x18LIFEの箱がある。拾いますか?'
    '\x18Got an HP box.',  # 53 = '\x18LIFEの箱を拾った。'
    '\x18Can\'t dive here.',  # 54 = '\x18ここは潜れない。'
    '\x18Can\'t swim up here.',  # 55 = '\x18ここは浮上できない。'
    '\x18It\'s a depth gauge. Take it?',  # 56 = '\x18水深計がある。拾いますか?'
    '\x18Got a depth gauge.',  # 57 = '\x18水深計を拾った。'
    '\x18It\'s a crystal. Take it?',  # 58 = '\x18水晶がある。取りますか?'
    '\x18Got a crystal.',  # 59 = '\x18水晶を取った。'
    '\x18It\'s a strangely shaped crystal. Take it?',  # 5a = '\x18おかしな形の水晶がある。取りますか?'
    '\x18Got a crystal magnet.',  # 5b = '\x18水晶の磁石を手に入れた。'
    'Let\'s try it out.',  # 5c = '試してみるかね。'
    'Wanna continue?',  # 5d = '続けるかい?'
    '\x18Can\'t drink anymore.',  # 5e = '\x18もう飲めない。'
    '\x18The chatfish\'s effects kicked in.',  # 5f = '\x18チャト効果が現われた。'
    '60',  # 60 = '60'
    'Backspace',  # 61 = 'BS'
    'Esc',  # 62 = 'ESC'
    'Shift',  # 63 = 'SHIFT'
    'Enter',  # 64 = 'リターン'
    ' key is lying here.\x15Take it?\x18',  # 65 = 'キーが落ちている。\x15拾いますか?\x18'
    ' key added to your keyboard.\x18',  # 66 = 'キーを拾いキーボードに取り付けた。\x18'
    '~\x18[SAVE POINT]... But you can\'t save with less than one box of HP.',  # 67 = '\x18[SAVE ZONE]... \x15しかし体力が一箱分以下ではセーブ出来ない。'
    'Uwaaah, t-t-take this!!\x15\x17(You suddenly throw a punch.)',  # 68 = 'うーー、ばし ばし ばしっ!!\x15\x17（あなたは、いきなり殴りかかった。）'
    '~Hey, what are you doing?! \x15Oh, I\'ll get you! *flail flail*',  # 69 = 'な \x11な \x11何するんだ、こいつ。\x15負けないぞー、ばしばしばしーっ!'
    'Woof, woof!! Grrrr!! \x15\x17(You suddenly bite them.)',  # 6a = 'ウワワ ワン。がぶっ!!\x15\x17（あなたは、いきなり相手にかみついた。）'
    '~Ow, ow, ow! It\'s payback time, grrr!',  # 6b = 'うわっ いててて。\x15仕返しだっ がぶがぶがぶっ。\x15キャイン キャイン!'
    'You calm down.',  # 6c = 'へーぜん。'
    '\x18A strong current pulls you up.',  # 6d = '\x18激しい水流に噴き上げられた。'
    '\x18You are caught in a current.',  # 6e = '\x18水流に巻き込まれた。'
    '\x18The upward current\'s too strong to dive.',  # 6f = '\x18水が噴き上げてくるので、潜れない。'
    '70',  # 70 = '70'
    '71',  # 71 = '71'
    '\x18The chatfish\'s effects wore off.',  # 72 = '\x18チャト効果が無くなった。'
    '73',  # 73 = '73'
    '74',  # 74 = '74'
    '75',  # 75 = '75'
    '76',  # 76 = '76'
    '77',  # 77 = '77'
    '78',  # 78 = '78'
    '79',  # 79 = '79'
    '7A',  # 7a = '7A'
    '7B',  # 7b = '7B'
    '7C',  # 7c = '7C'
    '7D',  # 7d = '7D'
    '7E',  # 7e = '7E'
    '7F',  # 7f = '7F'
    'POISON',  # 80 = 'POISON'
    'TRANSP',  # 81 = 'TRANSP'
    'MADMAD',  # 82 = 'MADMAD'
    '83',  # 83 = '83'
    '84',  # 84 = '84'
    '85',  # 85 = '85'
    '86',  # 86 = '86'
    '87',  # 87 = '87'
    '88',  # 88 = '88'
    '89',  # 89 = '89'
    '8A',  # 8a = '8A'
    '8B',  # 8b = '8B'
    '8C',  # 8c = '8C'
    '8D',  # 8d = '8D'
    '8E',  # 8e = '8E'
    '8F',  # 8f = '8F'
    '90',  # 90 = '90'
    '91',  # 91 = '91'
    '92',  # 92 = '92'
    '93',  # 93 = '93'
    '94',  # 94 = '94'
    '95',  # 95 = '95'
    '96',  # 96 = '96'
    '97',  # 97 = '97'
    '98',  # 98 = '98'
    '99',  # 99 = '99'
    '9A',  # 9a = '9A'
    '9B',  # 9b = '9B'
    '9C',  # 9c = '9C'
    '9D',  # 9d = '9D'
    '9E',  # 9e = '9E'
    '9F',  # 9f = '9F'
    'A0',  # a0 = 'A0'
    'Asdaf',  # a1 = 'ASDF'
    'Juklun',  # a2 = 'JKL;'
    'Rtyu',  # a3 = 'RTYU'
    'Ghu',  # a4 = 'GH'
    'Quey',  # a5 = 'QWE'
    'Iopa',  # a6 = 'IOP@'
    'Sawmill',  # a7 = '製材所'
    'Vybnym',  # a8 = 'VBNM'
    'Fivetown',  # a9 = '4567'
    'Kumiel',  # aa = 'クミエル'
    'Airport',  # ab = '空港'
    'Palace',  # ac = '宮殿'
    'Memorial',  # ad = '記念館'
    'Lake Town',  # ae = '湖底村'
    'AF',  # af = 'AF'
    'B0',  # b0 = 'B0'

    # 惑星クムドールに異変が起きたA.P.(ポーラ暦)405年。
    # 何処からともなく湧出する魔獣を蹴散らし、
    # 幾多の障壁を打ち破って再びクムドールに平和を取り戻したのは
    # 一人の地球人であったと伝えられている。
    # しかしハイテク兵器すら物ともしない魔獣達に対して使われた
    # 唯一の武器と言えば、もちろん魔法の剣などではなく
    # あなたもよくご存知かと思うが…
    # 最近そこいらでよく見かける、パソコンなどに付いている、
    # あのありふれたキーボードだったのだ。
    # 人々は異変の後、誰言うともなくキーボードの事を
    # 「クムドールの剣」と呼ぶようになった。

    '  It was the year 405 AP when the anomalies struck Kumdor.',
    'It is said that the hero who vanquished the monsters that',
    'appeared out of nowhere, broke through numerous barriers,',
    'and restored peace to Kumdor, was a single Earthling.',
    '  However, the only weapon that could defeat these beasts,',
    'unharmed as they were by even the most high-tech weaponry,',
    'was no magical sword or staff. Rather, it was a common',
    'piece of computer equipment you know as the keyboard.',
    '  After the anomalies--though it\'s unclear how this spread--',
    'the planet\'s inhabitants came to refer to the keyboard',
    'as "the Sword of Kumdor."',

    '',  # bc = 'BB'
    '',  # bd = 'BC'
    '',  # be = 'BD'
]
