[
    '00',  # 00 = '00'
    'All together, that\'ll be...\x15',  # 01 = 'そうしますと、全部で…\x15'
    ' spice.',  # 02 = 'スパイスになりますが。'
    'Oh, did you change your mind?',  # 03 = 'え? おやめになるんですか。'
    "I'm sorry, you don't have enough spice.",  # 04 = 'お客さん、スパイスが足りませんよ。'
    'You\'re carrying too much.',  # 05 = 'お客さん、荷物がいっぱいで\x15持ち切れませんよ。'
    'Thank you.',  # 06 = 'ありがとございました。'
    '',  # 07 = '07'
    '',  # 08 = '08'
    '',  # 09 = '09'
    '',  # 0a = '0A'
    '',  # 0b = '0B'
    '',  # 0c = '0C'
    '',  # 0d = '0D'
    '',  # 0e = '0E'
    '',  # 0f = '0F'
    '',  # 10 = '10'
    '~That ship seems to be the one the royals summoned from Solface... So what were you doing in there?',  # 11 = '落ちたのは王室がソルフェスに\x15派遣した船のようだが…\x15なんであんたが乗ってたんだい。'
    '~I hear the typist the royals sent here to help us has over 900 EXP.',  # 12 = '王室が助けを求めようとしたそのお方は\x15EXP.が 900以上もあると聞いている。'
    '~Jeez, you made quite the dent. The chief won\'t be happy.',  # 13 = 'あーあー、こんなでかい穴を作っちゃって。\x15村長にしかられるぞ。'
    '~Petrified keytrees, strange monsters running wild... What\'s happening to Kumdor?',  # 14 = 'クムの木は石化しちゃうし\x15変な魔獣はうろついてるし…\x15クムドールは一体どうしちゃったんだろ。'
    '~The petrified trees are blocking the way, so the only way north is through that cave.',  # 15 = '石化したクムの木が道をふさいでるから\x15北へ抜けるためには\x15洞窟を通らなきゃならないんだ。'
    '~If you\'re going to the cave, you\'ll want both the ASD and KL; keys.',  # 16 = '洞窟に入るなら、A,S,Dの他に\x15K,L,;キーも揃えた方がいいぜ。'
    '~The key shop is on the second floor.',  # 17 = 'キーショップなら2階だよ。'
    '~These are our finest keys.',  # 18 = 'キーはいかがでしょう。'
    '~We don\'t stock any other keys. They just don\'t sell well here.',  # 19 = '他のキーは、ここでは売れないから\x15置いてないんだよ。'
    '~This village is called Asdaf.\x15Juklun lies a bit east of here.',  # 1a = 'ジュクルン村は、このアズドフ村から−\x15東の方にちょっと行った所にあるよ。'
    '~Without the necessary keys, you can\'t enter the communications room.',  # 1b = '必要なキーを持ってないと\x15通信室には入れないよ。'
    'Today\'s my lucky day! It rained money!\x11\x15What\'s that? It\'s yours?\x11\x15Pshaw, you can\'t prove that!',  # 1c = 'へへへ、今日はいい日だ。\x15天から金が降ってきたよ。\x11\x15え? あんたのだって。\x11証拠が無いね。'
    'I mean, does it have your name on it?\x11\x15......\x11\x15Whoa! It actually does.',  # 1d = '名前が書いてある?\x11\x15……\x11\x15うわ! ほんとだ。'
    '\x18Got back 150 spice.',  # 1e = '\x18150スパイスを返してもらった。'
    'So many anomalies lately...\x15I hope some good anomalies happen, too.',  # 1f = '異変の多いこの頃だが…\x15いい異変も起こってほしいもんだよ。'
    '',  # 20 = '20'
    '~Ah, this is the exit.',  # 21 = 'こっちは出口専用ですよ。'
    '~Please leave from the other side.',  # 22 = '出る時は向こう側から出てくださいね。'
    '~Rumor has it this store resells goods from the market in Asdaf.',  # 23 = 'この店の品… アズドフ村のマーケットで\x15仕入れたっていうウワサだぜ。'
    '~I hear a "backspace key" lets you correct your mistakes.',  # 24 = 'BSキーがあると、ミスタイプした時\x15カーソルを戻せるんだって?'
    'Smoke moss, huh.\x11\x15Why would this place sell an antidote?',  # 25 = 'ケムリ苔?\x11\x15何で解毒剤なんか売ってるんだろ。'
    '~To shop here, you take a basket first. But I\'m sure you knew that already.',  # 26 = 'お買い物するなら、カゴを使うんですよ。\x15知ってますよね、そんな事。'
    '~Are they using the anomalies to hike up the prices?',  # 27 = '異変に便乗して、\x15値上げしたんじゃないかしら。'
    'Please return your basket.',  # 28 = 'お客さん、ご面倒でも−\x15カゴは元に戻しといてください。'
    'Practice?',  # 29 = '試してみるかね?'
    '~All the TVs have stopped working.',  # 2a = 'あれ以来テレビが映らなくなっちゃったよ。'
    '~The airwaves are disturbed. All our devices stopped working.',  # 2b = '電波は狂ってるし−\x15機械類はほとんど使えなくなっちゃった。'
    '~Oh, you\'re the one that made that hole. You\'d better apologize. The chief is upstairs.',  # 2c = 'あら、村の真ん中に大穴を開けちゃった人ね。\x15早めに謝っといた方がいいわよ。\x15村長なら上に居るから。'
    '~Kid, I believe you. You\'re the hero the royals are expecting from Solface.',  # 2d = 'わしは信じるよ。\x15あんたは、王室がソルフェスから\x15迎えようとしていた人に違いない。'
    '~I know you lost your abilities in the crash... But don\'t worry!',  # 2e = '落下のショックで\x15能力を失ってしまったようだが…\x15心配する事はない。'
    "~You can recover them, if you set your mind to it.\x15I suggest you visit the 'Big Hands'.",  # 2f = "その気があるなら、いずれ全部\x15取り戻す事が出来るだろう。\x15'大きな手'の所に行くといい。"
    '',  # 30 = '30'
    "~The weirdest of these anomalies are these 'hands' that sprouted in the comms room.\x15They're always mumbling stuff.",  # 31 = "異変の中でも一番不気味なのは\x15通信室に生えてきた'手'だね。\x15いつも偉そうに、何かブツブツ言ってるぜ。"
    '~At this rate, there\'ll be no more keywine by next year.',  # 32 = 'このまんまじゃ、来年は−\x15クム酒が飲めなくなるかもなー。'
    '~When a monster casts a spell at you, you\'re frozen in place as it saps the life from your body.',  # 33 = '魔獣から呪文を浴びせられると\x15足が動かなくなって\x15命をどんどん吸い取られてしまうんだ。'
    '~By chanting the same spell back at them, you can deal damage to the monsters.',  # 34 = '同じ呪文を唱え返すと\x15魔獣にダメージを与える事が出来るんだよ。'
    '~If a fight looks bad for you, run away sooner rather than later. You might escape with only minor injuries.',  # 35 = 'かなわないと思ったら、\x15早めに逃げた方がいいね。\x15軽傷を負うくらいで済むかもしれない。'
    '~Are you that weirdo that fell out of the sky?',  # 36 = 'あんたかい?\x15空から降ってきたっていう人は。'
    "~It's hard work doing such fine craftsmanship by hand.",  # 37 = '手作業で、こんな細かい仕事をするのって\x15疲れるなあ。'
    '~Those monsters are definitely not from this world. I\'ve defeated a few, but they just vanish without leaving a body.',  # 38 = 'あれは絶対、この世の生き物じゃないぜ。\x15三十体ほどやっつけたけど…\x15結局、跡形も無く消えてしまうんだ。'
    "~Guns, swords, cannons... we've tried them all, but the only thing that has any effect on them is 'spell mirroring'.",  # 39 = "ピストル、剣、大砲、ミサイル…\x15なんかはダメだね。全部試した訳じゃないけど\x15使えるのは'呪文返し'だけさ。"
    '~It\'s 5 spice to stay the night.\x15Please rest up if you\'re feeling weak.',  # 3a = 'ご宿泊は 5スパイスです。\x15体力が減ったら、お泊まりください。'
    '3B',  # 3b = '3B'
    'Thank you very much!\x15Your room is the one in the middle.',  # 3c = 'ありがとうございます。\x15真ん中のお部屋でどうぞ。'
    '~Please use the frontmost room.',  # 3d = 'では、一番手前のお部屋をお使いください。'
    '~Enjoy your stay.',  # 3e = 'ごゆっくりどうぞ。'
    'If there even still is a way to\x15the palace, it\'s probably to the north.\x11\x15',  # 3f = '宮殿へ行く道が残されているとしても\x15北の方角しか無いだろうね。\x11\x15'
    '40',  # 40 = '40'
    "~Real keyboard hero or not, you're too late. Things have gotten worse since the palace called for help.",  # 41 = 'もしあんたが本物のキーボード使いだとしても\x15手遅れだよ。王室が使いを出した頃は−\x15事態はもっとましだったんだ。'
    "~With *that* amount of EXP, nobody will believe you're the #1 typist in the Milky Way.",  # 42 = 'そのEXP.を見りゃ、\x15誰だってあんたが、銀河一のキーボード使い\x15だなんて思わないぜ。'
    "~You can't tell male and female Kumdorians apart? Weird. You Earthlings wear clothes! That's way harder!",  # 43 = 'クムドール人は男女の区別が付かないって?\x15失礼ね。\x15地球人なんか服着てるからもっと判んないわ。'
    '~With *that* amount of EXP...\x11\x15Wow, you must have improved a lot.',  # 44 = 'そのEXP.を見りゃ…\x11\x15ずい分腕を上げたね。'
    "~Well, that certainly can't be you.",  # 45 = 'ま、それがあんたじゃない事だけは確かだね。'
    'What? It is!?',  # 46 = 'えっ あるって???'
    "What's going on!?\x11\x15A spaceship came crashing down!\x11\x15Oh my stars, look at that hole!",  # 47 = "なんだ なんだ。\x11\x15船が墜落したらしい。\x11\x15うわっ、でかい穴!!"
    "Look, there's someone in there.\x11\x15Are they alive?\x11\x15......",  # 48 = "おい、誰かいるぜ。\x11\x15生きてるのかい?\x11\x15…………。"
    "Sorry. We're all sold out.",  # 49 = "すみません。\x15全部売り切れちゃいました。"
    "~After the anomalies started, rich folks hoarded up all the goods.",  # 4a = "異変が起きたもんで−\x15金持ちが、あわてて買い占めたんだと…。"
    "~It's dangerous to leave town without a full set of ASDF keys.",  # 4b = "A,S,D,Fキーを持たずに、町の外に出るのは\x15危険だぜ。"
    "~I've heard there's a useful key out there called 'Backspace'.",  # 4c = "世の中には、BSキーとか言う\x15便利なキーもあるらしいね。"
    "~You're thinking, \"there aren't any hotties on Kumdor\", right? That's the problem with you Earthlings: no taste!",  # 4d = 'あなた今、クムドールには美人がいない−\x15なんて思ったでしょ。\x11\x15地球人って審美眼が無いから困るわ。'
    "~It's customary to keep your Caps Lock off around here.",  # 4e = "ここではCAPSやカナのロックは\x15外しとくのが習慣だよ。"
    "\x17\x18(It seems to be broken.)",  # 4f = "\x17\x18（故障しているようだ。）"
    "",  # 50 = "50"
    "STAR CHEESE, 15 SPC, BLUBLUB.\x11\x15PURCHASE, BLUBLUB?",  # 51 = "星チーズ 一個 15スパイス。 ブク ブクッ\x11\x15イカガ デショウ。 ブク ブク ブク"
    "DROP SOMETHING.",  # 52 = "モテナイ。"
    "NEED MONEY.",  # 53 = "オカネ。 オカネ。"
    "\x18Bought Star Cheese.",  # 54 = "\x18星チーズを買った。"
    "~Oh, you came back. Do you think we'll get past this anomaly stuff?",  # 55 = "おお、よく戻ったな。\x11\x15ところで−\x15この異変は、どうにかなりそうかね。"
    "~What? You can talk to keytrees now? That's unbelievable!",  # 56 = "何、クムの木と話が出来るようになったと?\x11\x15それはすごい。"
    "~Not that you'd go there, though, right?",  # 57 = "まさか 行く気じゃないとは思うけど。"
    "~Wow, there's a passageway to the south now!?",  # 58 = "え 南に通路が出来ちゃった!?"
    "",  # 59 = "59"
    "",  # 5a = "5A"
    "",  # 5b = "5B"
    "",  # 5c = "5C"
    "",  # 5d = "5D"
    "",  # 5e = "5E"
    "",  # 5f = "5F"
    "",  # 60 = "60"
    "About the left hand home position...",  # 61 = "左手のホームポジションについて…"
    "Put your left index finger on F. (press f)",  # 62 = "左手の人差指はFの上に置く。（fを押せ）"
    "The middle finger goes on D. (press d)",  # 63 = "左手の中指はDの上に置く。（dを押せ）"
    "The left ring finger, on S. (press s)",  # 64 = "左手の薬指はSの上に置く。（sを押せ）"
    "And the left pinky on A. (press a)",  # 65 = "左手の小指はAの上に置く。（aを押せ）"
    "~We don't use the left thumb. The other four fingers should always return to this position.",  # 66 = "左手の親指は使わない。\x15それ以外の4本の指は−\x15いつも、この位置で待機せよ。"
    "That is all.",  # 67 = "以上。"
    "About the right hand home position...",  # 68 = "右手のホームポジションについて…"
    "Put the right index finger on J. (press j)",  # 69 = "右手の人差指はJの上に置く。（jを押せ）"
    "The middle finger goes on K. (press k)",  # 6a = "右手の中指はKの上に置く。（kを押せ）"
    "The right ring finger, on L. (press l)",  # 6b = "右手の薬指はLの上に置く。（lを押せ）"
    "And the right pinky on ;. (press ;)",  # 6c = "右手の小指は;の上に置く。（;を押せ）"
    "The right thumb rests on the space bar.\x15(press space)",  # 6d = "右手の親指はスペースバーの上に置く。\x15（スペースバーを押せ）"
    "~The five fingers on the right hand always return to this position.",  # 6e = "右手の5本の指は−\x15いつも、この位置で待機せよ。"
    "~To type +, hold Shift with the left pinky, then press ; with the other one. (press +)",  # 6f = "なお、+をタイプする時は−\x15左手の小指でSHIFTキーを押しながら\x15右手の小指で;キーを押す。（+をタイプせよ）"
    "",  # 70 = "70"
    "Welcome to Juklun.",  # 71 = "ジュクルン村です。 はい。"
    "~Fighting the monsters in the cave is one thing, but I can't get through the spell walls.",  # 72 = "洞窟の魔獣はなんとかなるけど、\x15呪文の壁を突破出来ないんだよ。"
    "~On the other side of the village is the lakeside village of Rtyu.",  # 73 = "洞窟を抜けると湖の手前にある\x15ルチュ村に行けるんだが…"
    "~Ever since the anomaly, we've stopped getting customers.",  # 74 = "異変以来、客がさっぱりだよ。"
    "~Will you spend the night for 5 spice?",  # 75 = "5スパイスですが、お泊まりになります?"
    "Hoho! Thaaank you.\x15Your room is right up ahead.",  # 76 = "ははっ、ありがとーございます。\x15手前のお部屋へどーぞ。"
    "~The entrance to the warehouse is on the north side.",  # 77 = "倉庫の入口は、北側にあるよ。"
    "~I heard a spaceship crashed down smack dab in the middle of Asdaf!",  # 78 = "アズドフ村の真ん中に−\x15宇宙船が落ちたらしいわね。"
    "~What's more, I heard there was some shabby Earthling found on board.",  # 79 = "なんでも− みすぼらしい地球人が\x15乗っていたっていう噂よ。"
    "~Weird, big hands have sprouted up in the basement of the warehouse.",  # 7a = "倉庫の地下に\x15でっかい手が生えてきたんだ。"
    "~That's pretty creepy.",  # 7b = "不気味だね。"
    "~I heard something similar happened over in Asdaf.",  # 7c = "アズドフ村でも\x15似たような事があるらしいよ。"
    "~Thanks for your patronage.",  # 7d = "まいど。"
    "",  # 7e = "7E"
    "",  # 7f = "7F"
    "",  # 80 = "80"
]
